stages:
  - build
  - push

variables:
  IMAGE_NAME: registry.example.com/your-namespace/nginx
  TAG: $CI_COMMIT_SHORT_SHA

build:
  stage: build
  script:
    - docker build -t $IMAGE_NAME:$TAG .
  only:
    - main

push:
  stage: push
  script:
    - echo $CI_JOB_TOKEN | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker push $IMAGE_NAME:$TAG
  only:
    - main
